server:
  port: 8080
spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
  rabbitmq:
    port: ${RM_PORT:1883}
    username: ${RM_USER:ureohfqi:ureohfqi}
    password: ${RM_PASSWORD}
    host: ${RM_HOST}

rm:
  queue:
    name: ${RM_QUEUE_NOTIFICATION:notification-vote-send}

app:
  url:
    validcpf: https://user-info.herokuapp.com/users