spring:
  rabbitmq:
    port: ${RM_PORT:5672}
    username: ${RM_USER:guest}
    password: ${RM_PASSWORD:guest}
    host: ${RM_HOST:localhost}
    ssl:
      enabled: false


rm:
  queue:
    name: ${RM_QUEUE_NOTIFICATION:notification-vote-send}
