server:
  port: ${SERVER_PORT:8080}

spring:
  profiles:
    active: ${APP_ENVIRONMENT}
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/assembly}



rm:
  queue:
    name: ${RM_QUEUE_NOTIFICATION:notification-vote-send}

app:
  url:
    validcpf: https://user-info.herokuapp.com/users